export const INDUSTRIES = [
  {
    id: "saas",
    title: "SaaS",
    blurb: "Deploys, billing, flags, keys, webhooks and the dashboards around them.",
    briefs: [
      { slug: "metrics-board", title: "Metrics board", level: 1, brief: "A dashboard stand with range keys and a bar chart. Press a range key. The columns rebuild slab by slab, and the read-out says 30d · signups +18%." },
      { slug: "usage-meter", title: "Usage meter", level: 1, brief: "A utility meter for API calls. Press +1K. The needle sweeps, the odometer rolls and the bill climbs, and the read-out says 12k calls · $24.00." },
      { slug: "feature-flags", title: "Feature flags", level: 2, brief: "A panel of slide switches beside a screen of users. Flip a switch. Its users light up on the screen, and the read-out says new-ui · on · 50% of users." },
      { slug: "api-key-vault", title: "API key vault", level: 3, brief: "A vault with a key-card slot. Press rotate. The old card flies out and a new one seats, and the read-out says rotated · 2 keys → 1." },
      { slug: "deploy-pipeline", title: "Deploy pipeline", level: 4, brief: "Three stage boxes on a rail with deploy and roll-back keys. Press deploy. A signal runs build → test → ship, and the read-out says live · v1.4.2." },
      { slug: "webhook-relay", title: "Webhook relay", level: 4, brief: "A relay hub wired to three endpoints. Press send. The event flies out, each endpoint answers and a failure retries, and the read-out says order.paid · delivered · 3/3." },
    ],
  },
  {
    id: "deeptech",
    title: "Deep tech",
    blurb: "Compute, chips, energy, robots and the instruments that run them.",
    briefs: [
      { slug: "ground-station", title: "Ground station", level: 2, brief: "A dish on a mount beside a shelter, with a satellite overhead. Press link. Pings climb to the satellite and its light comes on, and the read-out says linked · 12 ms." },
      { slug: "battery-stack", title: "Battery stack", level: 3, brief: "Four cells on a bus bar with a plug. Press charge. The plug seats and the cells fill level by level, and the read-out says 82% · 3.2 kWh." },
      { slug: "cryo-stack", title: "Cryo stack", level: 3, brief: "A dilution fridge of stacked plates. Press cool. The plates settle lowest first and the screen counts down, and the read-out says 10 mK · stable." },
      { slug: "gpu-cluster", title: "GPU cluster", level: 3, brief: "A rack of four GPU nodes beside a head node. Press train. The nodes light bottom to top and the loss curve falls, and the read-out says epoch 3 · loss 0.42." },
      { slug: "wafer-probe", title: "Wafer prober", level: 3, brief: "A probe head over a wafer of dies. Press probe. The head steps across six dies marking pass or fail, and the read-out says yield 83% · 5/6." },
      { slug: "pick-and-place", title: "Pick and place", level: 4, brief: "A gantry over a chip tray and a board. Press pick. The head lifts the next chip and seats it on the board, and the read-out says placed · 3 of 6." },
      { slug: "agent-relay", title: "Agent relay", level: 4, brief: "A rack of six coding agents, a Pushary relay, a MacBook, an iPhone and a savings board. Press run: the lead agent plans first and asks one question up front on the notch, then the phone. Approve the risky commands, and the read-out says done · saved 3h 4m and $3.73." },
    ],
  },
  {
    id: "marketing",
    title: "Marketing",
    blurb: "Channels, pages, budgets and campaigns, explained by pressing them.",
    briefs: [
      { slug: "billboard-flipper", title: "Billboard flipper", level: 1, brief: "A roadside billboard on a post with a lever. Press the lever. The panel turns to the next headline, and the read-out says variant B · 3 of 3." },
      { slug: "channel-dock", title: "Channel dock", level: 2, brief: "A dock with three channel cards and a screen. Press a card. It seats and a signal reaches the screen, and the read-out says meta ads linked · 1 of 3." },
      { slug: "funnel-hopper", title: "Funnel hopper", level: 2, brief: "A hopper with three sieves over a cup. Press the gate. Visitors drop through the sieves into the cup, and the read-out says 1,000 visits · 42 sign-ups." },
      { slug: "newsletter-press", title: "Newsletter press", level: 3, brief: "A letterpress beside an outbox. Press the platen. Printed sheets stack into the outbox one by one, and the read-out says 1,200 sent · 38% opened." },
      { slug: "budget-rack", title: "Budget rack", level: 4, brief: "Three ad cards with stacks of budget coins. Press run. The weakest ad pauses and its coins fly onto the winner, and the read-out says day 4 · ad c paused." },
      { slug: "campaign-hub", title: "Campaign hub", level: 4, brief: "A hub wired to three channel screens. Press launch. One campaign runs down three cables and each channel lights in its own format, and the read-out says live on 3 channels." },
    ],
  },
  {
    id: "agents",
    title: "Agents",
    blurb: "The figures that started isokit: computers, approvals and phones.",
    briefs: [
      { slug: "tally-counter", title: "Tally counter", level: 1, brief: "A hand tally counter with a plunger and a reset knob. Press the plunger. The count rolls on, and the read-out says count 0004." },
      { slug: "sound-board", title: "Sound board", level: 1, brief: "A pad of thirteen keys, one per sound. Press a pad. It plays its sound, and the read-out names it." },
      { slug: "approval-pad", title: "Approval pad", level: 2, brief: "A pad with allow and deny keys under a request screen. Press allow. The request clears and the next one arrives, and the read-out says allowed · back to work." },
      { slug: "edge-box", title: "Edge box", level: 2, brief: "A small computer beside a stepped folder sorter. Press a folder. It lifts and the box reads it offline, and the read-out says contract.pdf · read." },
      { slug: "phone", title: "Phone", level: 2, brief: "A phone on a dock showing an agent's request. Press approve. The card clears and the next question arrives, and the read-out says approved · 3 waiting." },
      { slug: "page-press", title: "Page press", level: 3, brief: "A press with page blocks over a bed. Press publish. The blocks drop into place lowest first and the address goes live, and the read-out says live · 4 blocks." },
      { slug: "desk-computer", title: "Desk computer", level: 4, brief: "A desk computer with a keyboard. Press it to switch on, then type. Keys sink and the prompt appears on its screen, and the read-out says on · 18 chars · key q." },
    ],
  },
  {
    id: "fintech",
    title: "Fintech",
    blurb: "Payments, vaults, ledgers and the counters money moves across.",
    briefs: [
      { slug: "card-terminal", title: "Card terminal", level: 1, brief: "A countertop card terminal with a keypad. Press OK. The screen goes from amount to approved and the status light comes on, and the read-out says €24.90 · approved." },
      { slug: "savings-jar", title: "Savings jar", level: 1, brief: "A glass savings jar with a coin slot. Press the coin. It drops in and the level rises, and the read-out says saved €120 · goal 40%." },
      { slug: "cash-machine", title: "Cash machine", level: 2, brief: "A cash machine wired to a vault. Press withdraw. A signal runs to the vault and notes slide out of the slot, and the read-out says €60 · balance €1,240." },
      { slug: "vault-door", title: "Vault door", level: 3, brief: "A round vault door with a wheel and five bolts. Press the wheel. The bolts retract one after another and the door swings open, and the read-out says unlocked · 5 of 5 bolts." },
      { slug: "ledger-press", title: "Ledger press", level: 3, brief: "A ledger book under a stamping press. Press the lever. Entries stamp onto the page top to bottom, and the read-out says 12 entries · balanced." },
      { slug: "exchange-counter", title: "Exchange counter", level: 4, brief: "A currency counter with two coin trays and a rate board. Press EUR or USD, then swap. Coins fly between trays at the board's rate, and the read-out says 100 EUR → 108 USD." },
    ],
  },
  {
    id: "health",
    title: "Health",
    blurb: "Bedside devices, lab instruments and the doses they measure.",
    briefs: [
      { slug: "ecg-monitor", title: "ECG monitor", level: 1, brief: "A bedside ECG monitor with lead keys. Press a lead key. The trace switches lead, and the read-out says lead II · 72 bpm." },
      { slug: "infusion-pump", title: "Infusion pump", level: 2, brief: "An infusion pump on a pole with a line to a bag. Press start. Drops run down the line and the rate shows on its screen, and the read-out says 50 ml/h · running." },
      { slug: "blood-pressure-cuff", title: "Blood pressure cuff", level: 2, brief: "A monitor with a hose to a cuff. Press measure. The cuff inflates and the reading returns up the hose, and the read-out says 118/76 · normal." },
      { slug: "pill-sorter", title: "Pill sorter", level: 3, brief: "A seven-day pill sorter under a dispenser. Press fill. Pills drop into each day's cell from Monday on, and the read-out says 7 of 7 days · filled." },
      { slug: "centrifuge", title: "Centrifuge", level: 3, brief: "A lab centrifuge with six tubes. Press spin. The lid locks, the rotor runs up and the tubes separate one by one, and the read-out says 6 samples · 3,000 rpm." },
      { slug: "lab-analyzer", title: "Lab analyser", level: 4, brief: "An analyser with a sample rack and an arm. Press load, then run. The arm carries each tube to the reader and results fill the screen, and the read-out says 4 of 4 · 1 flagged." },
    ],
  },
  {
    id: "logistics",
    title: "Logistics",
    blurb: "Parcels, pallets, docks and cranes, and where each box ends up.",
    briefs: [
      { slug: "parcel-locker", title: "Parcel locker", level: 1, brief: "A bank of parcel lockers with a keypad. Press a code key. One door swings open, and the read-out says locker 7 · open." },
      { slug: "shipping-scale", title: "Shipping scale", level: 2, brief: "A parcel scale wired to a label printer. Press weigh. A signal runs to the printer and a label feeds out, and the read-out says 2.4 kg · label printed." },
      { slug: "dock-door", title: "Dock door", level: 2, brief: "A loading-dock door with a call button and a truck light. Press call. A signal lights the truck bay and the door rolls up, and the read-out says dock 2 · truck in." },
      { slug: "conveyor-sorter", title: "Conveyor sorter", level: 3, brief: "A conveyor with three diverter arms over bins. Press sort. Parcels roll down the belt and peel off into their bins in turn, and the read-out says 6 sorted · 2 · 3 · 1." },
      { slug: "pallet-wrapper", title: "Pallet wrapper", level: 3, brief: "A pallet on a turntable with a film carriage. Press wrap. The carriage climbs layer by layer as the pallet turns, and the read-out says 4 layers · secured." },
      { slug: "container-crane", title: "Container crane", level: 4, brief: "A quay crane over a ship and a truck. Press hoist, then trolley. The spreader lifts a container and carries it onto the truck, and the read-out says box 3 of 6 · on truck." },
    ],
  },
  {
    id: "energy",
    title: "Energy",
    blurb: "Meters, panels, turbines and the grid that carries what they make.",
    briefs: [
      { slug: "smart-meter", title: "Smart meter", level: 1, brief: "A home electricity meter with a display key. Press the key. The screen cycles today, this week and tariff, and the read-out says 4.2 kWh today." },
      { slug: "solar-tracker", title: "Solar tracker", level: 2, brief: "A solar panel on a tilting mount, cabled to a home battery. Press tilt. The panel turns to the sun and a signal runs down the cable, and the read-out says 3.1 kW · charging." },
      { slug: "ev-charger", title: "EV charger", level: 2, brief: "A charging post with a cable to a parked car. Press plug. The connector seats and a signal runs into the car, and the read-out says 11 kW · 34% → 80%." },
      { slug: "wind-turbine", title: "Wind turbine", level: 3, brief: "A turbine with a nacelle and three blades. Press start. The brake releases, the blades ramp up and the output bar fills in steps, and the read-out says 12 m/s · 2.1 MW." },
      { slug: "heat-pump", title: "Heat pump", level: 3, brief: "An outdoor fan unit piped to an indoor tank. Press heat. The fan spins up, refrigerant pulses round the loop and the tank fills to temperature, and the read-out says 55 °C · COP 3.8." },
      { slug: "substation", title: "Substation", level: 4, brief: "A substation with three breakers and a load bank. Press a breaker, then reroute. Power travels the live bus and the dead feeder goes dark, and the read-out says feeder B · rerouted · 0 outages." },
    ],
  },
  {
    id: "manufacturing",
    title: "Manufacturing",
    blurb: "Presses, printers, mills and robot cells on the factory floor.",
    briefs: [
      { slug: "stamping-press", title: "Stamping press", level: 1, brief: "A hydraulic press with a die and a palm button. Press the button. The ram comes down and a blank becomes a bracket, and the read-out says part 18 · ok." },
      { slug: "filament-printer", title: "Filament printer", level: 2, brief: "A desktop 3D printer with a spool. Press print. Filament runs from the spool to the nozzle and the first layer traces the bed, and the read-out says layer 1 of 40 · 12 min." },
      { slug: "quality-gauge", title: "Quality gauge", level: 2, brief: "A go/no-go gauge over two bins. Press check. The part slides through the gauge and drops into pass or reject, and the read-out says 97% pass · lot 3 · #34 go." },
      { slug: "assembly-line", title: "Assembly line", level: 3, brief: "A short line with three stations. Press run. A chassis moves station to station and each adds a part, and the read-out says 3 of 3 stations · unit 12 built." },
      { slug: "cnc-mill", title: "CNC mill", level: 3, brief: "A mill with a spindle over a stock block. Press cycle start. The spindle steps through four pockets, and the read-out says op 4 of 4 · ±0.02 mm." },
      { slug: "robot-cell", title: "Robot cell", level: 4, brief: "A welding cell with a turntable and a light curtain. Press load, then weld. The table turns the part in and the arm welds four seams, and the read-out says 4 seams · cell safe." },
    ],
  },
  {
    id: "retail",
    title: "Retail",
    blurb: "Shelves, tills, machines and the checkout in between.",
    briefs: [
      { slug: "shelf-label", title: "Shelf label", level: 1, brief: "An electronic shelf label on a shelf edge. Press the update key. The price flips, and the read-out says €2.49 · was €2.99." },
      { slug: "loyalty-stamp", title: "Loyalty stamp", level: 1, brief: "A coffee loyalty card under a rubber stamp. Press the stamp. One more cup is inked, and the read-out says 7 of 10 · free coffee at 10." },
      { slug: "checkout-till", title: "Checkout till", level: 2, brief: "A till wired to a receipt printer. Press total. A signal runs to the printer and the receipt feeds out, and the read-out says 4 items · €18.40." },
      { slug: "vending-machine", title: "Vending machine", level: 3, brief: "A vending machine with a coil grid and a keypad. Press B2. The coil turns, the can drops and the tray light comes on, and the read-out says B2 · €1.50 · dispensed · 2 left." },
      { slug: "restock-shelf", title: "Restock shelf", level: 3, brief: "A store shelf with gaps and a restock cart. Press restock. The gaps fill from left to right, and the read-out says 8 of 8 facings · full." },
      { slug: "self-checkout", title: "Self checkout", level: 4, brief: "A self-checkout with a scanner, a bagging scale and a card reader. Press scan for each item, then pay. Items travel into the bag and the scale confirms, and the read-out says 3 items · €9.20 · paid." },
    ],
  },
  {
    id: "media",
    title: "Media",
    blurb: "Studios, mics, encoders and the switchers that put them on air.",
    briefs: [
      { slug: "on-air-light", title: "On-air light", level: 1, brief: "A studio ON AIR sign with a wall switch. Press the switch. The sign lights and its clock starts, and the read-out says on air · 00:00." },
      { slug: "turntable", title: "Turntable", level: 2, brief: "A record player with a tonearm. Press start. The arm swings onto the next track and the platter spins up, and the read-out says side A · track 2." },
      { slug: "podcast-mic", title: "Podcast mic", level: 2, brief: "A mic on an arm, cabled to a recorder. Press record. A level signal runs down the cable and the recorder's meter moves, and the read-out says recording · 00:12." },
      { slug: "encoder-stack", title: "Encoder stack", level: 3, brief: "A broadcast encoder with three output bars. Press encode. 1080p, 720p and 480p fill one after another, and the read-out says 3 renditions · ready." },
      { slug: "strobe-studio", title: "Strobe studio", level: 3, brief: "A photo set with three strobes and a camera. Press shoot. The strobes fire in sequence and the frame counter ticks, and the read-out says frame 12 · f/8." },
      { slug: "vision-mixer", title: "Vision mixer", level: 4, brief: "A vision mixer with preview and program monitors. Press a camera, then cut. Its picture moves from preview to program and the tally light follows; fade to black resets, and the read-out says cam 2 · live." },
    ],
  },
  {
    id: "security",
    title: "Security",
    blurb: "Badges, keys, cameras and the rooms they keep closed.",
    briefs: [
      { slug: "badge-reader", title: "Badge reader", level: 1, brief: "A badge reader beside a door. Press the badge. The reader lights up and the door slides open, and the read-out says badge 0412 · door open." },
      { slug: "cctv-camera", title: "CCTV camera", level: 2, brief: "A camera on a wall bracket, cabled to a recorder. Press pan. The camera turns and a signal runs to the recorder, and the read-out says zone 3 · recording." },
      { slug: "security-key", title: "Security key", level: 2, brief: "A hardware key in a laptop port. Press its gold disc. A challenge runs in and the laptop unlocks, and the read-out says signed in · 2FA." },
      { slug: "firewall-rack", title: "Firewall rack", level: 3, brief: "A firewall appliance with a row of port lights. Press block. The ports drop suspicious traffic one after another, and the read-out says 3 threats · blocked." },
      { slug: "hsm-module", title: "HSM module", level: 3, brief: "A hardware security module in a rack with tamper seals. Press sign. The seals check in turn and a signature prints on the screen, and the read-out says signed · key 4 · sealed." },
      { slug: "soc-desk", title: "SOC desk", level: 4, brief: "A security desk with an alert board and response keys. Press an alert, then isolate. The infected laptop moves into quarantine and the board clears, and the read-out says 1 isolated · 0 open." },
    ],
  },
  {
    id: "mobility",
    title: "Mobility",
    blurb: "Crossings, docks, garages and the signals that move traffic.",
    briefs: [
      { slug: "crossing-light", title: "Crossing light", level: 1, brief: "A pedestrian crossing light with a call button. Press the button. The figure turns green, and the read-out says walk · 12 s." },
      { slug: "bike-dock", title: "Bike dock", level: 1, brief: "A city-bike dock with a release button. Press release. One bike unlocks, and the read-out says bike 08 · 4 left." },
      { slug: "scooter-dock", title: "Scooter dock", level: 2, brief: "A shared e-scooter beside a phone on a stand. Press unlock. A signal runs from the phone to the scooter and its deck light comes on, and the read-out says unlocked · €0.25/min." },
      { slug: "car-wash", title: "Car wash", level: 3, brief: "A drive-through car wash. Press start. Brushes, foam and dryer pass over the car one after another, and the read-out says 3 of 3 · clean." },
      { slug: "parking-gate", title: "Parking gate", level: 3, brief: "A garage barrier with a level board. Press enter. The barrier lifts, the car rolls in and free spaces count down floor by floor, and the read-out says level 2 · 14 free." },
      { slug: "signal-box", title: "Signal box", level: 4, brief: "A railway signal box with two levers and a track diagram. Press points, then signal. The train travels the switched track and the block clears, and the read-out says train 2 · platform 3." },
    ],
  },
  {
    id: "education",
    title: "Education",
    blurb: "Classroom objects that teach by being pressed.",
    briefs: [
      { slug: "abacus", title: "Abacus", level: 1, brief: "An abacus with ten beads per rod. Press a bead. It slides across, and the read-out says 3 + 4 = 7." },
      { slug: "flashcard-box", title: "Flashcard box", level: 1, brief: "A box of flashcards. Press flip. The card turns to its answer, and the read-out says 8 of 20 · correct." },
      { slug: "desk-globe", title: "Desk globe", level: 2, brief: "A globe on a stand beside a lamp. Press spin. The globe turns to the next country and the lamp marks it, and the read-out says Kenya · Nairobi." },
      { slug: "titration-stand", title: "Titration stand", level: 3, brief: "A burette over a flask. Press the tap. Drops fall one by one until the flask turns colour, and the read-out says 12.4 ml · endpoint." },
      { slug: "telescope-mount", title: "Telescope mount", level: 3, brief: "A classroom telescope on a tripod. Press track. The tube slews to Saturn in three steps and the eyepiece view fills, and the read-out says Saturn · tracking." },
      { slug: "quiz-buzzers", title: "Quiz buzzers", level: 4, brief: "Three quiz buzzers and a scoreboard. Press a buzzer, then judge. The point travels from the question card to that team, and the read-out says team B · 4 points." },
    ],
  },
] as const

export type IndustryEntry = (typeof INDUSTRIES)[number]
export type IndustryId = IndustryEntry["id"]
export type Brief = IndustryEntry["briefs"][number]
