export { Box, type BoxProps } from "./components/box"
export { Plate, type PlateProps } from "./components/plate"
export { Press, type PressProps } from "./components/press"
export { SoundToggle, type SoundToggleProps } from "./components/sound-toggle"
export { curve } from "./geometry/curve"
export { corners, frame } from "./geometry/framing"
export { front, path, project, side, top, type Vec2 } from "./geometry/projection"
export { hull, outline, radius } from "./geometry/rounded-outline"
export { Cursor, type CursorProps } from "./guided-motion/cursor"
export { Flight, type FlightProps } from "./guided-motion/flight"
export { Ripple, type RippleProps } from "./guided-motion/ripple"
export { Signal, type SignalProps } from "./guided-motion/signal"
export { type DemoPhase, type DemoTap, type DemoTapOptions, useDemoTap } from "./guided-motion/use-demo-tap"
export type { Box3, Fit, SoundConfig, SoundName, SoundOptions, Vec3 } from "./schema"
export { configureSound, playSound, primeSound } from "./sound/sound-player"
export { soundPreference } from "./sound/sound-store"
export { useSoundEnabled } from "./sound/use-sound-enabled"
